Repository nbc-9gling/news-feed, pull requests merged in 2023-11, with the labels that each got.

#7 feature 프로젝트 셋업
  .env
  .prettierrc
  jsconfig.json
  package.json
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/App.css
  src/App.js
  src/App.test.js
  src/firebase/myfirebase.js
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/detail_post/view/index.js
  src/pages/home/view/index.js
  src/pages/layout/header.jsx
  src/pages/layout/sidebar.jsx
  src/pages/layout/view/index.js
  src/pages/manage_post/view/index.js
  src/routers/index.js
  src/styles/globalstyles.js
  src/styles/theme.js
  test.txt
  yarn.lock
Labels: 기능

#12 feature layout/sidebar컴포넌트 생성 , 쓰로틀 함수 생성,아코디언버튼 컴포넌트 생성
  .env
  src/fb/myfirebase.js
  src/index.js
  src/pages/common/accordion.jsx
  src/pages/home/view/index.js
  src/pages/layout/sidebar.jsx
  src/pages/layout/view/index.js
  src/pages/layout/view/sidebar.jsx
  src/utils/usethrottle.js
Labels: UI

#17 [Feature/carousel] 캐로셀 UI
  public/index.html
  src/data/tagData.js
  src/pages/home/view/carousel.jsx
  src/pages/home/view/components/carouselTag.jsx
  src/pages/home/view/components/feedCard.jsx
  src/pages/home/view/feedList.jsx
  src/pages/home/view/index.js
  src/pages/layout/footer.jsx
  src/pages/layout/view/index.js
  src/setupTests.js
  src/styles/globalstyles.js
Labels: UI

#18 [Feature/cardlist] 카드리스트 UI 병합
  src/pages/home/view/components/feedCard.jsx
Labels: UI

#19 Feature/header
  src/pages/layout/header.jsx
  src/pages/layout/view/index.js
Labels: 기능, UI

#20 feature/ 2차 셋업
  package.json
  src/App.js
  src/components/avatar.jsx
  src/components/hashtag.jsx
  src/components/likeicon.jsx
  src/components/svgbox.jsx
  src/data/tagData.js
  src/data/tagData.json
  src/pages/home/carouselTag.jsx
  src/pages/home/feedCard.jsx
  src/pages/home/view/carousel.jsx
  src/pages/home/view/feedList.jsx
  src/pages/layout/header.jsx
  src/pages/layout/view/footer.jsx
  src/pages/layout/view/header.jsx
  src/pages/layout/view/index.js
  src/pages/layout/view/modal.jsx
  src/pages/layout/view/sidebar.jsx
  src/pages/manage_post/view/index.js
  src/redux/config/configStore.js
  src/redux/modules/modalState.js
  yarn.lock
Labels: 수정

#22 Feature/layout 유저 데이터 및 포스트 데이터 실시간 수신대기
  src/data/sidebar/accordion_data.js
  src/fb/myfirebase.js
  src/pages/layout/auth_btns.jsx
  src/pages/layout/login.jsx
  src/pages/layout/signup.jsx
  src/pages/layout/view/header.jsx
  src/pages/layout/view/index.js
  src/pages/layout/view/modal.jsx
  src/pages/layout/view/sidebar.jsx
  src/redux/config/configStore.js
  src/redux/modules/authState.js
  src/redux/modules/firestoreState.js
  src/utils/format/number.js
Labels: 기능

#23 Feature/header
  src/components/likeicon.jsx
  src/pages/layout/auth_btns.jsx
  src/pages/layout/login.jsx
  src/pages/layout/signup.jsx
  src/pages/layout/view/header.jsx
  src/pages/layout/view/index.js
  src/pages/layout/view/modal.jsx
Labels: 기능

#24 [Feature/editor form] Storage 업로드 기능
  src/fb/myfirebase.js
  src/pages/manage_post/editorForm.jsx
  src/pages/manage_post/inputImg.jsx
  src/pages/manage_post/previewImg.jsx
  src/utils/useForm.js
Labels: 기능, UI

#25 [Feature/cardfilter] 병합
  src/data/tagData.json
  src/pages/home/carouselTag.jsx
  src/pages/home/feedCard.jsx
  src/pages/home/feedHashtag.jsx
  src/pages/home/view/carousel.jsx
  src/pages/home/view/feedList.jsx
  src/pages/home/view/index.js
Labels: 수정

#26 feature/setup: 셋업 및 병합
  src/pages/layout/view/header.jsx
  src/pages/layout/view/index.js
  src/redux/config/configStore.js
  src/redux/modules/storage.js
Labels: 수정

#27 Feature/layout
  src/pages/common/accordion.jsx
  src/pages/layout/view/index.js
  src/pages/layout/view/sidebar.jsx
  src/redux/modules/firestoreState.js
  src/routers/index.js
Labels: 기능

#28 [Feature/slider filter] 카테고리에 따른 필터 구현
  src/data/tagData.json
  src/pages/home/carouselTag.jsx
  src/pages/home/feedCard.jsx
  src/pages/home/view/carousel.jsx
  src/pages/home/view/feedList.jsx
  src/pages/home/view/index.js
  src/routers/index.js
Labels: 기능

#30 Feature/header
  src/pages/layout/auth_btns.jsx
  src/pages/layout/login.jsx
  src/pages/layout/signup.jsx
  src/pages/layout/view/header.jsx
  src/pages/layout/view/modal.jsx
Labels: 기능

#31 [Feature/editorform] editorform 업로드 완료
  src/pages/manage_post/editorForm.jsx
  src/pages/manage_post/fieldset.jsx
  src/pages/manage_post/inputImg.jsx
  src/pages/manage_post/previewImg.jsx
  src/pages/manage_post/view/editorForm.jsx
  src/pages/manage_post/view/index.js
  src/pages/manage_post/view/index.jsx
  src/utils/useForm.js
Labels: 기능, UI

#32 chore: 병합 (#15)
  src/pages/home/carouselTag.jsx
  src/pages/home/view/feedList.jsx
Labels: 기능, UI

#34 Feature/header
  src/pages/layout/auth_btns.jsx
  src/pages/layout/google_login.jsx
  src/pages/layout/login.jsx
  yarn.lock
Labels: 기능

#35 feature:setup/ 4차 셋업
  src/pages/home/feedCard.jsx
  src/pages/home/feedHashtag.jsx
  src/pages/home/view/feedList.jsx
  src/pages/home/view/index.js
  src/pages/layout/view/index.js
  src/pages/manage_post/view/editorForm.jsx
  yarn.lock
Labels: 수정

#38 Feature/header
  src/pages/layout/auth_btns.jsx
  src/pages/layout/githublogin.jsx
  src/pages/layout/login.jsx
  src/pages/layout/signup.jsx
  src/pages/layout/view/header.jsx
  src/pages/layout/view/modal.jsx
  src/redux/modules/usersFirestoreState.js
Labels: 기능

#39 feature 실시간 수신대기 수정(임시) #36
  src/pages/layout/view/index.js
Labels: 수정

#40 Feature/layout
  src/pages/layout/signup.jsx
  src/pages/layout/view/index.js
  src/pages/layout/view/sidebar.jsx
  src/redux/modules/usersFirestoreState.js
Labels: 수정

#42 [Feature/slider filter] 카테고리별, 해시태그별 필터 구현
  src/components/hashtag.jsx
  src/data/foodTagData.json
  src/pages/home/carousel.jsx
  src/pages/home/carouselTag.jsx
  src/pages/home/feedCard.jsx
  src/pages/home/feedHashtag.jsx
  src/pages/home/feedList.jsx
  src/pages/home/view/carousel.jsx
  src/pages/home/view/index.js
Labels: 기능, UI

#43 feature 디테일페이지 생성 및 5차셋업
  src/pages/detail_post/test.jsx
  src/pages/detail_post/view/index.js
  src/pages/detail_post/view/index.jsx
  src/pages/home/feedCard.jsx
  src/pages/home/feedList.jsx
  src/pages/home/view/index.js
  src/pages/layout/githublogin.jsx
  src/pages/layout/google_login.jsx
  src/pages/layout/login.jsx
  src/pages/layout/signup.jsx
  src/pages/layout/view/footer.jsx
  src/pages/layout/view/header.jsx
  src/pages/layout/view/index.js
  src/pages/layout/view/modal.jsx
  src/pages/layout/view/sidebar.jsx
  src/pages/manage_post/view/editorForm.jsx
  src/redux/modules/postsFirestoreState.js
  src/routers/index.js
  src/utils/useForm.js
Labels: UI, 수정

#44 chore: 병합
  src/pages/detail_post/test.jsx
  src/pages/home/carousel.jsx
  src/pages/layout/login.jsx
  src/pages/layout/signup.jsx
  src/pages/layout/view/modal.jsx
Labels: 수정

#46 Feature/header
  src/pages/layout/auth_btns.jsx
  src/pages/layout/github_login.jsx
  src/pages/layout/google_login.jsx
  src/pages/layout/login.jsx
  src/pages/layout/signup.jsx
  src/pages/layout/view/modal.jsx
Labels: 기능

#47 Feature/header
  src/pages/layout/github_login.jsx
  src/pages/layout/google_login.jsx
  src/redux/modules/usersFirestoreState.js
Labels: UI

#48 fix : github 로그인 닉네임 안뜨는 거 수정 (#14)
  src/redux/modules/usersFirestoreState.js
Labels: bug

#49 feat: 카테고리별 해시태그 구현 수정 (#15)
  src/data/foodTagData.json
  src/pages/home/carousel.jsx
  src/pages/home/feedList.jsx
Labels: 기능

#50 feature사이드바 로그인 수신대기상태일때 로딩바 추가
  src/components/spinner.jsx
  src/pages/layout/view/index.js
  src/pages/layout/view/modal.jsx
  src/pages/layout/view/sidebar.jsx
Labels: UI

#51 Detail page
  src/components/listOption.jsx
  src/pages/detail_post/test.jsx
  src/utils/useLink.js
Labels: 기능, UI

#53 feature 마이페이지 추가 및 이미지 전체 로딩추가, 및 마무리작업
  src/components/avatar.jsx
  src/components/hashtag.jsx
  src/components/svgbox.jsx
  src/pages/detail_post/detailPostContent.jsx
  src/pages/detail_post/view/index.jsx
  src/pages/home/feedCard.jsx
  src/pages/home/feedList.jsx
  src/pages/home/view/index.js
  src/pages/layout/auth_btns.jsx
  src/pages/layout/github_login.jsx
  src/pages/layout/google_login.jsx
  src/pages/layout/login.jsx
  src/pages/layout/signup.jsx
  src/pages/layout/view/index.js
  src/pages/layout/view/modal.jsx
  src/pages/layout/view/sidebar.jsx
  src/pages/manage_post/inputImg.jsx
  src/pages/manage_post/view/editorForm.jsx
  src/pages/modifyuser/useForm.js
  src/pages/modifyuser/view/index.jsx
  src/redux/modules/postsFirestoreState.js
  src/redux/modules/usersFirestoreState.js
  src/routers/index.js
  src/utils/useDate.js
Labels: 기능, 수정

#54 feature 최종 오류 수정중
  src/pages/home/feedCard.jsx
  src/pages/home/feedList.jsx
  src/pages/home/view/index.js
  src/pages/layout/view/index.js
  src/pages/modifyuser/view/index.jsx
Labels: bug

#57 Update feedCard.jsx
  src/pages/home/feedCard.jsx
Labels: bug

#58 [docs] README.md 작성
  README.md
Labels: 문서
